{% set version = "1.0.5" %}

package:
  name: paegan-transport
  version: {{ version }}

source:
  fn: paegan-transport-{{ version }}.tar.gz
  url: https://github.com/axiom-data-science/paegan-transport/archive/{{ version }}.tar.gz
  sha256: 292a97e355fe5549f1441bb89ef4c8f0ba13920c7096c7695edd24146743d5ac

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - paegan
    - fiona
    - requests
    - redis-py  # [not win]
    - geojson
    - pytables

test:
  imports:
    - paegan.transport
    - paegan.transport.bathymetry
    - paegan.transport.controllers  # [not win]
    - paegan.transport.export
    - paegan.transport.forcers
    - paegan.transport.models
    - paegan.transport.models.behaviors
    - paegan.transport.parallel_manager
    - paegan.transport.particles
    - paegan.transport.shoreline

about:
  home: https://github.com/axiom-data-science/paegan-transport
  license: GPL-3.0
  summary: 'Paegan-Transport - The parallellized Langragian transport model for NetCDF/OPeNDAP data, written on top of Paegan.'

extra:
  recipe-maintainers:
    - ocefpaf
