# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lI7bj9O5tXLik4juTxvk8Hqok9pYh02rx51infbkrDrzQOeX7Eacs6tz2HH2IOaPcDLQOwqhRl4i6Bfvkf3Ud9EfOIZJz+8ZzbwaEMWQIH9fhb/Ack62eofCzn8uHMUt6nyI+gbUVWoxqy4ScERSBbNA9qilF4rrd48wb/T70ncfpzc82GUWJjSjfnFjoH0pa5j/qlTWy5O/b6JzC2IyUO0N75rRS/q6UrS+UrjQwjll96A4J0Ig451of8Sbb14Rc5YPcOkpLcaYBOa3HGbjNR0dYsFJS4qEHPnI7M11//YKMyLwW2mm23eGcg8aMPQcYAnQOlpzUKuW0rcGIMjP1Fn953mOZHGat2iTt6XGIXNCyHF9SBwo8sCNf//vkla3xVPyRhe0LMdwGp8/SY0OtKMmPzfhupBzqpIHmi7+F6OlHD8pRmI07/Gw1+Qu7T9UDR58bnE1i/9W7TsOD3w3fsyW+EIVtx512s8JP8GXfveAQXiYmQEpLFQnbfuu37HerMyZYuDcy9BflI0Ngw0TWxhrSj2VF13eCoWw1DcpWjatJ5CDXrWhjzixndfOqhJvGqg/BSSQZwXPpLjrl9m1Qqa6luW9rB4IhYYASc4sv/NMN6rrvSreXmKgfoQpQ6P1ZdjqbUgb1l2prdCZNaKgRj3aIKNoQjhdL0C1zf3uNEc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
