appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lI7bj9O5tXLik4juTxvk8Hqok9pYh02rx51infbkrDrzQOeX7Eacs6tz2HH2IOaPcDLQOwqhRl4i6Bfvkf3Ud9EfOIZJz+8ZzbwaEMWQIH9fhb/Ack62eofCzn8uHMUt6nyI+gbUVWoxqy4ScERSBbNA9qilF4rrd48wb/T70ncfpzc82GUWJjSjfnFjoH0pa5j/qlTWy5O/b6JzC2IyUO0N75rRS/q6UrS+UrjQwjll96A4J0Ig451of8Sbb14Rc5YPcOkpLcaYBOa3HGbjNR0dYsFJS4qEHPnI7M11//YKMyLwW2mm23eGcg8aMPQcYAnQOlpzUKuW0rcGIMjP1Fn953mOZHGat2iTt6XGIXNCyHF9SBwo8sCNf//vkla3xVPyRhe0LMdwGp8/SY0OtKMmPzfhupBzqpIHmi7+F6OlHD8pRmI07/Gw1+Qu7T9UDR58bnE1i/9W7TsOD3w3fsyW+EIVtx512s8JP8GXfveAQXiYmQEpLFQnbfuu37HerMyZYuDcy9BflI0Ngw0TWxhrSj2VF13eCoWw1DcpWjatJ5CDXrWhjzixndfOqhJvGqg/BSSQZwXPpLjrl9m1Qqa6luW9rB4IhYYASc4sv/NMN6rrvSreXmKgfoQpQ6P1ZdjqbUgb1l2prdCZNaKgRj3aIKNoQjhdL0C1zf3uNEc=}
conda_forge_output_validation: true
