travis:
  secure:
    BINSTAR_TOKEN: VJ8hrcXaSH6z5GgBw7pNUp8mnFxG11HovHcJjU8bKpDn9h68UP3hS5Ke8nmPQ6YtANPO3u+8hSvFN4EorjqKhuYkT9SgprcUQ09Qn73BbR1SZ6sjcA9nw4NlFGxEjwe+5TeEVIi7GhWxCb6NmgF+PkJ8A+Z7y5snPMaazFkIuKBaxhXWfcqa2w8WKdoWTIqmWvWy7x5u/3Dh5qB4mtWLc33KSjmpF/x+YcAeNynEgqg4/JSLmDKYOL4FR8KWs4UHa3CiQOu/LfyAm+dx2aos7gzaLZFoKqmkS/ESJAmoR2AglY4H7SfQ8Cl/MrIIjVpdZKLbMQbCLl4iN/+zCrefxT7NGNHVKxrMf6uHcXQN9cDBYDp/c8D1yZlMRnea7yCl6gDABuzsiHWt/vWn3BLilmktCUOUOBoiWTw5YbbPIwe3MphqIUozfZeODKWfZcwaWjfru+S+Vsw5M1WBcR//Mg4UznyUNVvmqTDj/VYepB23t1YcpCc2B6q++MDGGUiV80FZcIxG7Pj3Qk8m2KqD05burP/kGiOiUIFqqI9IYwvLSEM+Awd0HlUGdVwjvEvADUQdyV46SO6V/JBNDTpW9xdWBgFnLk6kYO6BfAUmBzc04BKwwPl8CmctYJFn0EV4YByPDlqHWuO/nXuZ5KdUtrs8YYQ8fPbGjmG9MnBlKSc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
